"" vimrc configuration
"================================================
"" Plugings
"================================================
call plug#begin('~/.vim/plugged')

Plug 'itchyny/lightline.vim'
" Plug 'vim-airline/vim-airline'
" Plug 'vim-airline/vim-airline-themes'

Plug 'yggdroot/indentline'
Plug 'preservim/nerdcommenter'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'jiangmiao/auto-pairs'
Plug 'godlygeek/tabular'

" Plug 'neoclide/coc.nvim', {'branch': 'release'}
" Plug 'honza/vim-snippets'
" Plug 'wsdjeg/JavaUnit.vim'
" Plug 'puremourning/vimspector'
" Plug 'zongou/JavaRun'
Plug 'zongou/mvnExecJava'

call plug#end()
filetype on
filetype plugin on
filetype plugin indent on

"================================================
"" General settings
"================================================

"------ Meta ------"
" clear all autocommands! (this comment must be on its own line)
autocmd!

set nocompatible                " break away from old vi compatibility
set fileformats=unix,dos,mac    " support all three newline formats
set viminfo=                    " don't use or save viminfo files
source $VIMRUNTIME/defaults.vim		" Get the defaults that most users want

"------ Console UI & Text display ------"
set cmdheight=1                 " explicitly set the height of the command line
set showcmd                     " Show (partial) command in status line.
set number                      " yay line numbers
set ruler                       " show current position at bottom
set noerrorbells                " don't whine
set visualbell t_vb=            " and don't make faces
set lazyredraw                  " don't redraw while in macros
set scrolloff=3                 " keep at least 5 lines around the cursor
set nowrap                        " soft wrap long lines
set nolist                        " show invisible characters
set listchars=tab:>·,trail:·    " but only show tabs and trailing whitespace
set report=0                    " report back on all changes
set shortmess=atI               " shorten messages and don't show intro
set wildmenu                    " turn on wild menu :e <Tab>
set wildmode=list:longest       " set wildmenu to list choice

"------ Text editing and searching behavior ------"
set clipboard=unnamed	" yank to the system register (*) by default
set nohlsearch                  " turn off highlighting for searched expressions
set incsearch                   " highlight as we search however
set matchtime=5                 " blink matching chars for .x seconds
set mouse=a                     " try to use a mouse in the console (wimp!)
set ignorecase                  " set case insensitivity
set smartcase                   " unless there's a capital letter
set completeopt=menu,longest,preview " more autocomplete <Ctrl>-P options
set nostartofline               " leave my cursor position alone!
set backspace=2                 " equiv to :set backspace=indent,eol,start
set textwidth=0                 " we like 80 columns
set showmatch                   " show matching brackets
set iskeyword+=_,$,@,%,#,-		"not to split word"
set formatoptions=tcrql         " t - autowrap to textwidth
                                " c - autowrap comments to textwidth
                                " r - autoinsert comment leader with <Enter>
                                " q - allow formatting of comments with :gq
                                " l - don't format already long lines

"------ Indents and tabs ------"
set autoindent                  " set the cursor at same indent as line above
set smartindent                 " try to be smart about indenting (C-style)
set expandtab                   " expand <Tab>s with spaces; death to tabs!
set shiftwidth=4                " spaces for each step of (auto)indent
set softtabstop=4               " set virtual tab stop (compat for 8-wide tabs)
set tabstop=4                   " for proper display of files with tabs
set shiftround                  " always round indents to multiple of shiftwidth
set copyindent                  " use existing indents for new indents
set preserveindent              " save as much indent structure as possible
filetype plugin indent on       " load filetype plugins and indent settings

"------ History,backup and swapfile ------"
set confirm                     " prompt to save when modified
set history=1000
set nobackup
set noswapfile
set autoread		" auto read when file is changed from outside

"------ netrw ------"
" let g:netrw_sort_by = 'time'
" let g:netrw_sort_direction = 'reverse'
let g:netrw_browse_split = 4
" let g:netrw_liststyle = 3
let g:netrw_banner = 0
" let g:netrw_winsize = 25

"------ general key bindings ------"
" select all
nnoremap <C-a> gg0vG$
inoremap <C-a> <ESC>gg0vG$
" Ctrl + s to save
inoremap <C-s> <ESC>:w<CR>a
" Copy to system clipboard
nnoremap<silent> <C-p> :call CopyToSystem()<CR>
function CopyToSystem()
    let bExistTermuxApi=!system('dpkg -s termux-api >/dev/null 2>&1; echo $?')
    if bExistTermuxApi
        let tmpfile = system('mktemp')
        call writefile(getreg('0',1,1), tmpfile, 'b')
        call system('cat "'. tmpfile . '" |termux-clipboard-set')
        call system('termux-toast "copied to clipboard."')
        call system('rm "' . tmpfile . '"' )
    else
        echom "termux-api not installed."
    endif
endfunc

"================================================
" theme
"================================================
"------ colorscheme ------"
:colorscheme monokai
" :set background=light
" :set background=dark
 
"------ hilight ------"
" --- Popup menu
" :hi Pmenu ctermfg=16 ctermbg=252 cterm=NONE guifg=#697383 guibg=#d3d1cc gui=NONE
" :hi PmenuSel ctermfg=16 ctermbg=45 cterm=bold guifg=#555f6f guibg=#bdbbb6 gui=bold
" :hi PmenuSbar ctermbg=188 cterm=NONE guibg=#dfddd7 gui=NONE
" :hi PmenuThumb ctermbg=247 cterm=NONE guibg=#929cad gui=NONE
" --- coc highlight
" ---  error
" :hi CocErrorSign ctermfg=124 ctermbg=NONE
" :hi CocErrorHighlight ctermfg=124 ctermbg=NONE cterm=underline,bold guifg=#697383 guibg=#d3d1cc gui=NONE
" :hi CocErrorFloat ctermfg=124 ctermbg=252 cterm=NONE guifg=#697383 guibg=#d3d1cc gui=NONE
" ---  warning
" :hi CocWarningSign ctermfg=124 ctermbg=NONE cterm=bold guifg=#697383 guibg=#d3d1cc gui=NONE
" :hi CocWarningHighlight ctermfg=124 ctermbg=252 cterm=NONE guifg=#697383 guibg=#d3d1cc gui=NONE
" :hi CocWarningFloat ctermfg=124 ctermbg=252 cterm=NONE guifg=#697383 guibg=#d3d1cc gui=NONE

"================================================
"" run code
"================================================
"press F5 to run C, C++...
map <F5> :call RunCode()<CR>
inoremap <F5> <ESC>:call RunCode()<CR>
func! RunCode()
        exec "w"
    if expand('%:t') == 'termux.properties'
        exec "!termux-reload-settings"
    elseif &filetype == 'c' || &filetype == 'cpp'
        exec "ter ++shell clang % -o %< ; ./%<"
    elseif &filetype == 'go'
        exec "term go run %"
    elseif &filetype == 'java'
        if exists("g:existsMvnExecJavaPlugin")
            call MvnExecJava()
        " if JavaRun is installed and is has src folder
        elseif exists('*JavaRun') && fnamemodify(getcwd(), ':t') == "src"
            exec "JavaRun"
        " no JavaRun
        else
            exec "term java %"
        endif
    elseif &filetype == 'python'
        exec "term python %"
    elseif &filetype == 'sh'
        exec "term bash %"
    elseif &filetype == 'javascript'
        exec "term node %"
    elseif &filetype == 'vim'
        exec "source %"
    else 
        echo "filetype: " &filetype
    endif
endfunc
"debug C, C++...
map <F8> :call Rungdb()<CR>
func! Rungdb()
    exec "w"
    exec "!g++ % -g -o %<"
    exec "!gdb ./%<"
endfunc

"================================================
" Plugin settings
"================================================
"------ lightline settings ------"
set laststatus=2
if !has('gui_running')
    set t_Co=8
endif
set noshowmode

let g:lightline = {
      \ 'colorscheme': 'default',
      \ 'component_function': {
      \   'fileformat': 'LightlineFileformat',
      \   'fileencoding': 'LightLineFileencoding',
      \   'filetype': 'LightlineFiletype',
      \ },
      \ }

function! LightlineFileformat()
  return winwidth(0) > 70 ? &fileformat : ''
endfunction

function! LightLineFileencoding() 
    if empty(get(g:, 'coc_status', '')) && empty(get(b:, 'coc_diagnostic_info', {})) 
        return winwidth(0) < 70 ? &fileformat : &fileencoding
    endif
    return trim(coc#status())
endfunction

function! LightlineFiletype()
  return winwidth(0) > 70 ? (&filetype !=# '' ? &filetype : 'no ft') : ''
endfunction

"------ commenter ------"
let mapleader=","

" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1

" Use compact syntax for prettified multi-line comments
let g:NERDCompactSexyComs = 1

" Align line-wise comment delimiters flush left instead of following code indentation
let g:NERDDefaultAlign = 'left'

" Set a language to use its alternate delimiters by default
let g:NERDAltDelims_java = 1

" Add your own custom formats or override the defaults
let g:NERDCustomDelimiters = { 'c': { 'left': '/**','right': '*/' } }

" Allow commenting and inverting empty lines (useful when commenting a region)
let g:NERDCommentEmptyLines = 1

" Enable trimming of trailing whitespace when uncommenting
let g:NERDTrimTrailingWhitespace = 1

" Enable NERDCommenterToggle to check all selected lines is commented or not
let g:NERDToggleCheckAllLines = 1

"================================================
"" COC settings
"================================================
let g:coc_disable_startup_warning=1
"------ COC DEFALUT CONFIGURATION ------"
"------ END CONFIGURATION ------"
" coc-react-refactor
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)
" coc-java-debug
" function! JavaStartDebugCallback(err, port)
"   execute "cexpr! 'Java debug started on port: " . a:port . "'"
"   call vimspector#LaunchWithSettings({ "configuration": "Java Attach", "AdapterPort": a:port })
" endfunction
"
" function JavaStartDebug()
"   call CocActionAsync('runCommand', 'vscode.java.startDebugSession', function('JavaStartDebugCallback'))
" endfunction
"
" nmap <F5> :call JavaStartDebug()<CR>
